DROP TABLE D2L_ORGANIZATIONAL_UNIT_ANCESTOR_LOAD;

CREATE TABLE D2L_ORGANIZATIONAL_UNIT_ANCESTOR_LOAD (
  OrgUnitId NUMBER(10) NOT NULL,
  AncestorOrgUnitId NUMBER(10) NOT NULL,
  OrgUnitType NVARCHAR2(100) DEFAULT NULL,
  OrgUnitCode NVARCHAR2(100) DEFAULT NULL,
  OrgUnitSingleAncestor NUMBER(1) DEFAULT NULL,
  AncestorOrgUnitType NVARCHAR2(100) DEFAULT NULL,
  AncestorOrgUnitCode NVARCHAR2(100) DEFAULT NULL
);

CREATE UNIQUE INDEX D2L_ORGANIZATIONAL_UNIT_ANCESTOR_LOAD_PK ON D2L_ORGANIZATIONAL_UNIT_ANCESTOR_LOAD (OrgUnitId, AncestorOrgUnitId);

QUIT;
