-- gsu mods

DROP TABLE D2L_ORGANIZATIONAL_UNIT_ANCESTOR;

CREATE TABLE D2L_ORGANIZATIONAL_UNIT_ANCESTOR (
  OrgUnitId NUMBER(10) NOT NULL,
  AncestorOrgUnitId NUMBER(10) NOT NULL,
  OrgUnitType NVARCHAR2(100) DEFAULT NULL,
  OrgUnitCode NVARCHAR2(100) DEFAULT NULL,
  OrgUnitSingleAncestor NUMBER(1) DEFAULT NULL,
  AncestorOrgUnitType NVARCHAR2(100) DEFAULT NULL,
  AncestorOrgUnitCode NVARCHAR2(100) DEFAULT NULL
);

CREATE UNIQUE INDEX D2L_ORGANIZATIONAL_UNIT_ANCESTOR_PK ON D2L_ORGANIZATIONAL_UNIT_ANCESTOR (OrgUnitId, AncestorOrgUnitId);
CREATE INDEX IDX_D2L_ORGANIZATIONAL_UNIT_ANCESTOR_CODE ON D2L_ORGANIZATIONAL_UNIT_ANCESTOR (OrgUnitCode, AncestorOrgUnitCode);
CREATE INDEX IDX_D2L_ORGANIZATIONAL_UNIT_ANCESTOR_ANCESTORORGUNITID ON D2L_ORGANIZATIONAL_UNIT_ANCESTOR (AncestorOrgUnitId);
CREATE INDEX IDX_D2L_ORGANIZATIONAL_UNIT_ANCESTOR_ANCESTORORGUNITCODE ON D2L_ORGANIZATIONAL_UNIT_ANCESTOR (AncestorOrgUnitCode);
CREATE INDEX IDX_D2L_ORGANIZATIONAL_UNIT_ANCESTOR_ANCESTORORGUNITIDTYPE ON D2L_ORGANIZATIONAL_UNIT_ANCESTOR (AncestorOrgUnitId, OrgUnitType);
CREATE INDEX IDX_D2L_ORGANIZATIONAL_UNIT_ANCESTOR_ORGUNITID ON D2L_ORGANIZATIONAL_UNIT_ANCESTOR (OrgUnitId);
CREATE INDEX IDX_D2L_ORGANIZATIONAL_UNIT_ANCESTOR_ORGUNITCODE ON D2L_ORGANIZATIONAL_UNIT_ANCESTOR (OrgUnitCode);
CREATE INDEX IDX_D2L_ORGANIZATIONAL_UNIT_ANCESTOR_ORGUNITIDANCESTORTYPE ON D2L_ORGANIZATIONAL_UNIT_ANCESTOR (OrgUnitId, AncestorOrgUnitType);
CREATE BITMAP INDEX IDX_D2L_ORGANIZATIONAL_UNIT_ANCESTOR_ORGUNITTYPE ON D2L_ORGANIZATIONAL_UNIT_ANCESTOR (OrgUnitType);
CREATE BITMAP INDEX IDX_D2L_ORGANIZATIONAL_UNIT_ANCESTOR_ANCESTORORGUNITTYPE ON D2L_ORGANIZATIONAL_UNIT_ANCESTOR (AncestorOrgUnitType);
CREATE BITMAP INDEX IDX_D2L_ORGANIZATIONAL_UNIT_ANCESTOR_SINGLEANCESTOR ON D2L_ORGANIZATIONAL_UNIT_ANCESTOR (OrgUnitSingleAncestor);

QUIT;
