-- gsu mods

DROP TABLE D2L_ENROLLMENT_AND_WITHDRAWAL;

CREATE TABLE D2L_ENROLLMENT_AND_WITHDRAWAL (
  LogId NUMBER(20) NOT NULL,
  UserId NUMBER(10) DEFAULT NULL,
  OrgUnitId NUMBER(10) DEFAULT NULL,
  RoleId NUMBER(10) DEFAULT NULL,
  Action VARCHAR2(100 CHAR) DEFAULT NULL,
  ModifiedByUserId NUMBER(10) DEFAULT NULL,
  EnrollmentDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  IsLatest NUMBER(1) DEFAULT NULL
);

CREATE UNIQUE INDEX D2L_ENROLLMENT_AND_WITHDRAWAL_PK ON D2L_ENROLLMENT_AND_WITHDRAWAL (LogId);
CREATE INDEX IDX_D2L_ENROLLMENT_AND_WITHDRAWAL_USERORG ON D2L_ENROLLMENT_AND_WITHDRAWAL (UserId, OrgUnitId, LogId);
CREATE BITMAP INDEX IDX_D2L_ENROLLMENT_AND_WITHDRAWAL_ROLEID ON D2L_ENROLLMENT_AND_WITHDRAWAL (RoleId);
CREATE BITMAP INDEX IDX_D2L_ENROLLMENT_AND_WITHDRAWAL_ACTION ON D2L_ENROLLMENT_AND_WITHDRAWAL (Action);
CREATE BITMAP INDEX IDX_D2L_ENROLLMENT_AND_WITHDRAWAL_ENROLLMENTTYPE ON D2L_ENROLLMENT_AND_WITHDRAWAL (EnrollmentType);
CREATE BITMAP INDEX IDX_D2L_ENROLLMENT_AND_WITHDRAWAL_ISLATEST ON D2L_ENROLLMENT_AND_WITHDRAWAL (IsLatest);

QUIT;
