DROP TABLE D2L_AWARD_ISSUED_LOAD;

CREATE TABLE D2L_AWARD_ISSUED_LOAD (
  AwardId NUMBER(20) DEFAULT NULL,
  OrgUnitId NUMBER(20) DEFAULT NULL,
  UserId NUMBER(20) DEFAULT NULL,
  IssuedBy NUMBER(10) DEFAULT NULL,
  IssueDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  ExpiryDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  IssuedId NUMBER(20) NOT NULL,
  Criteria NVARCHAR2(2000) DEFAULT NULL,
  Evidence NVARCHAR2(2000) DEFAULT NULL,
  RevokedDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  RevokedReason NVARCHAR2(2000) DEFAULT NULL,
  RevokedBy NUMBER(20) DEFAULT NULL,
  LastModifiedBy NUMBER(20) DEFAULT NULL,
  LastModifiedDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  Version NUMBER(20) DEFAULT NULL
);

CREATE UNIQUE INDEX D2L_AWARD_ISSUED_LOAD_PK ON D2L_AWARD_ISSUED_LOAD (
  IssuedId
);

QUIT;
