-- gsu mods

DROP TABLE D2L_USER_ENROLLMENT;

CREATE TABLE D2L_USER_ENROLLMENT (
  OrgUnitId NUMBER(10) NOT NULL,
  UserId NUMBER(10) NOT NULL,
  RoleName NVARCHAR2(120) DEFAULT NULL,
  EnrollmentDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  EnrollmentType VARCHAR2(100 CHAR) DEFAULT NULL,
  RoleId NUMBER(10) DEFAULT NULL
);

CREATE UNIQUE INDEX D2L_USER_ENROLLMENT_PK ON D2L_USER_ENROLLMENT (OrgUnitId, UserId);
CREATE INDEX IDX_D2L_USER_ENROLLMENT_ORGUNITID ON D2L_USER_ENROLLMENT (OrgUnitId);
CREATE INDEX IDX_D2L_USER_ENROLLMENT_USERID ON D2L_USER_ENROLLMENT (UserId);
CREATE INDEX IDX_D2L_USER_ENROLLMENT_ENROLLMENTDATE ON D2L_USER_ENROLLMENT (EnrollmentDate);
CREATE BITMAP INDEX IDX_D2L_USER_ENROLLMENT_ROLEID ON D2L_USER_ENROLLMENT (RoleId);
CREATE BITMAP INDEX IDX_D2L_USER_ENROLLMENT_ROLENAME ON D2L_USER_ENROLLMENT (RoleName);
CREATE BITMAP INDEX IDX_D2L_USER_ENROLLMENT_ENROLLMENTTYPE ON D2L_USER_ENROLLMENT (EnrollmentType);

QUIT;
