DROP TABLE D2L_ORGANIZATIONAL_UNIT;

CREATE TABLE D2L_ORGANIZATIONAL_UNIT (
  OrgUnitId NUMBER(10) NOT NULL,
  Organization NVARCHAR2(100) DEFAULT NULL,
  Type NVARCHAR2(100) DEFAULT NULL,
  Name NVARCHAR2(256) DEFAULT NULL,
  Code NVARCHAR2(100) DEFAULT NULL,
  StartDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  EndDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  IsActive NUMBER(1) DEFAULT NULL,
  CreatedDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  IsDeleted NUMBER(1) DEFAULT NULL,
  DeletedDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  RecycledDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  Version NUMBER(20) DEFAULT NULL,
  OrgUnitTypeId NUMBER(10) DEFAULT NULL,
  CourseOfferingId NUMBER(10) DEFAULT NULL,
  CourseTemplateId NUMBER(10) DEFAULT NULL,
  DepartmentId NUMBER(10) DEFAULT NULL,
  ProgramId NUMBER(10) DEFAULT NULL,
  CollegeId NUMBER(10) DEFAULT NULL,
  SemesterId NUMBER(10) DEFAULT NULL,
  SisTermCode VARCHAR2(6 CHAR) DEFAULT NULL,
  SisCRN VARCHAR2(5 CHAR) DEFAULT NULL,
  SisXlsCode VARCHAR2(15 CHAR) DEFAULT NULL,
  SisSubjCrse VARCHAR2(15 CHAR) DEFAULT NULL,
  SisDeptCode VARCHAR2(15 CHAR) DEFAULT NULL
);

CREATE UNIQUE INDEX D2L_ORGANIZATIONAL_UNIT_PK ON D2L_ORGANIZATIONAL_UNIT (OrgUnitId);
CREATE INDEX IDX_D2L_ORGANIZATIONAL_UNIT_NAME ON D2L_ORGANIZATIONAL_UNIT(Name);
CREATE INDEX IDX_D2L_ORGANIZATIONAL_UNIT_CODE ON D2L_ORGANIZATIONAL_UNIT(Code);
CREATE INDEX IDX_D2L_ORGANIZATIONAL_UNIT_STARTDATE ON D2L_ORGANIZATIONAL_UNIT(StartDate);
CREATE INDEX IDX_D2L_ORGANIZATIONAL_UNIT_ENDDATE ON D2L_ORGANIZATIONAL_UNIT(EndDate);
CREATE INDEX IDX_D2L_ORGANIZATIONAL_UNIT_CREATEDDATE ON D2L_ORGANIZATIONAL_UNIT(CreatedDate);
CREATE INDEX IDX_D2L_ORGANIZATIONAL_UNIT_DELETEDDATE ON D2L_ORGANIZATIONAL_UNIT(DeletedDate);
CREATE INDEX IDX_D2L_ORGANIZATIONAL_UNIT_RECYCLEDDATE ON D2L_ORGANIZATIONAL_UNIT(RecycledDate);
CREATE INDEX IDX_D2L_ORGANIZATIONAL_UNIT_VERSION ON D2L_ORGANIZATIONAL_UNIT(Version);
CREATE INDEX IDX_D2L_ORGANIZATIONAL_UNIT_COURSEOFFERINGID ON D2L_ORGANIZATIONAL_UNIT(CourseOfferingId);
CREATE INDEX IDX_D2L_ORGANIZATIONAL_UNIT_COURSETEMPLATEID ON D2L_ORGANIZATIONAL_UNIT(CourseTemplateId);
CREATE INDEX IDX_D2L_ORGANIZATIONAL_UNIT_TERMCRN ON D2L_ORGANIZATIONAL_UNIT(SisTermCode, SisCrn);
CREATE INDEX IDX_D2L_ORGANIZATIONAL_UNIT_TERMXLS ON D2L_ORGANIZATIONAL_UNIT(SisTermCode, SisXlsCode);
CREATE INDEX IDX_D2L_ORGANIZATIONAL_UNIT_SUBJCRSE ON D2L_ORGANIZATIONAL_UNIT(SisSubjCrse);
CREATE BITMAP INDEX IDX_D2L_ORGANIZATIONAL_UNIT_ORGANIZATION ON D2L_ORGANIZATIONAL_UNIT(Organization);
CREATE BITMAP INDEX IDX_D2L_ORGANIZATIONAL_UNIT_TYPE ON D2L_ORGANIZATIONAL_UNIT(Type);
CREATE BITMAP INDEX IDX_D2L_ORGANIZATIONAL_UNIT_ISACTIVE ON D2L_ORGANIZATIONAL_UNIT(IsActive);
CREATE BITMAP INDEX IDX_D2L_ORGANIZATIONAL_UNIT_ISDELETED ON D2L_ORGANIZATIONAL_UNIT(IsDeleted);
CREATE BITMAP INDEX IDX_D2L_ORGANIZATIONAL_UNIT_ORGUNITTYPEID ON D2L_ORGANIZATIONAL_UNIT(OrgUnitTypeId);
CREATE BITMAP INDEX IDX_D2L_ORGANIZATIONAL_UNIT_DEPARTMENTID ON D2L_ORGANIZATIONAL_UNIT(DepartmentId);
CREATE BITMAP INDEX IDX_D2L_ORGANIZATIONAL_UNIT_PROGRAMID ON D2L_ORGANIZATIONAL_UNIT(ProgramId);
CREATE BITMAP INDEX IDX_D2L_ORGANIZATIONAL_UNIT_COLLEGEID ON D2L_ORGANIZATIONAL_UNIT(CollegeId);
CREATE BITMAP INDEX IDX_D2L_ORGANIZATIONAL_UNIT_SEMESTERID ON D2L_ORGANIZATIONAL_UNIT(SemesterId);
CREATE BITMAP INDEX IDX_D2L_ORGANIZATIONAL_UNIT_TERMCODE ON D2L_ORGANIZATIONAL_UNIT(SisTermCode);
CREATE BITMAP INDEX IDX_D2L_ORGANIZATIONAL_UNIT_DEPTCODE ON D2L_ORGANIZATIONAL_UNIT(SisDeptCode);

QUIT;
