DROP TABLE D2L_QUIZ_USER_ANSWER;

CREATE TABLE D2L_QUIZ_USER_ANSWER (
  AttemptId NUMBER(20) NOT NULL,
  QuestionId NUMBER(20) DEFAULT NULL,
  QuestionVersionId NUMBER(20) DEFAULT NULL,
  TimeCompleted TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  QuestionNumber NUMBER(10) DEFAULT NULL,
  D2LComment NVARCHAR2(2000) DEFAULT NULL,
  SortOrder NUMBER(10) DEFAULT NULL,
  Score DECIMAL(19, 9) DEFAULT NULL,
  Page NUMBER(10) DEFAULT NULL,
  SectionId NUMBER(20) DEFAULT NULL,
  ObjectId NUMBER(20) NOT NULL,
  OutOf DECIMAL(19, 9) DEFAULT NULL,
  TimeStarted TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  IsBonus NUMBER(1) DEFAULT NULL,
  IsDeleted NUMBER(1) DEFAULT NULL,
  LastModified TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  LastModifiedBy NUMBER(10) DEFAULT NULL,
  QuizTimeCompleted TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL
);

CREATE UNIQUE INDEX D2L_QUIZ_USER_ANSWER_PK ON D2L_QUIZ_USER_ANSWER (
  AttemptId,
  ObjectId
);

QUIT;
