DROP TABLE D2L_USER;

CREATE TABLE D2L_USER (
  UserId NUMBER(10) NOT NULL,
  UserName NVARCHAR2(540) DEFAULT NULL,
  OrgDefinedId NVARCHAR2(512) DEFAULT NULL,
  FirstName NVARCHAR2(128) DEFAULT NULL,
  MiddleName NVARCHAR2(128) DEFAULT NULL,
  LastName NVARCHAR2(128) DEFAULT NULL,
  IsActive NUMBER(1) DEFAULT NULL,
  Organization VARCHAR2(512 CHAR) DEFAULT NULL,
  ExternalEmail NVARCHAR2(512) DEFAULT NULL,
  SignupDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  FirstLoginDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  Version NUMBER(20) DEFAULT NULL,
  OrgRoleId NUMBER(10) DEFAULT NULL,
  OrgRoleName NVARCHAR2(240) DEFAULT NULL,
  LastAccessed TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  SisPIDM NUMBER(8,0) DEFAULT NULL,
  SisPantherId VARCHAR2(9 CHAR) DEFAULT NULL
);

CREATE UNIQUE INDEX D2L_USER_PK ON D2L_USER (UserId);
CREATE INDEX IDX_D2L_USER_USERNAME ON D2L_USER(UserName);
CREATE INDEX IDX_D2L_USER_ORGDEFINEDID ON D2L_USER(OrgDefinedId);
CREATE INDEX IDX_D2L_USER_FIRSTNAME ON D2L_USER(LastName, FirstName);
CREATE INDEX IDX_D2L_USER_EXTERNALEMAIL ON D2L_USER(ExternalEmail);
CREATE INDEX IDX_D2L_USER_SIGNUPDATE ON D2L_USER(SignupDate);
CREATE INDEX IDX_D2L_USER_FIRSTLOGINDATE ON D2L_USER(FirstLoginDate);
CREATE INDEX IDX_D2L_USER_LASTACCESSED ON D2L_USER(LastAccessed);
CREATE INDEX IDX_D2L_USER_VERSION ON D2L_USER(Version);
CREATE INDEX IDX_D2L_USER_PIDM ON D2L_USER(SisPIDM);
CREATE INDEX IDX_D2L_USER_PANTHERID ON D2L_USER(SisPantherId);
CREATE BITMAP INDEX IDX_D2L_USER_ISACTIVE ON D2L_USER(IsActive);
CREATE BITMAP INDEX IDX_D2L_USER_ORGANIZATION ON D2L_USER(Organization);
CREATE BITMAP INDEX IDX_D2L_USER_ORGROLEID ON D2L_USER(OrgRoleId);
CREATE BITMAP INDEX IDX_D2L_USER_ORGROLEROLE ON D2L_USER(OrgRoleName);

QUIT;
