ALTER TABLE D2L_COURSE_COPY_LOG_LOAD
  ADD StatusId NUMBER(10) DEFAULT NULL
;

ALTER TABLE D2L_COURSE_COPY_LOG
  ADD StatusId NUMBER(10) DEFAULT NULL
;

ALTER TABLE D2L_LTI_LINK_LOAD
  MODIFY Url NVARCHAR2(4000) DEFAULT NULL
;
ALTER TABLE D2L_LTI_LINK_LOAD
  ADD (
    LastModifiedBy NUMBER(10) DEFAULT NULL,
    IsDeleted NUMBER(1) DEFAULT NULL
  )
;

ALTER TABLE D2L_LTI_LINK
  MODIFY Url NVARCHAR2(4000) DEFAULT NULL
;
ALTER TABLE D2L_LTI_LINK
  ADD (
    LastModifiedBy NUMBER(10) DEFAULT NULL,
    IsDeleted NUMBER(1) DEFAULT NULL
  )
;

DROP TABLE D2L_LTI_LINK_SHARED_LOAD;
DROP TABLE D2L_LTI_LINK_SHARED;
DROP TABLE D2L_SURVEY_QUESTION_ANSWER_OPTIONS_LOAD;
DROP TABLE D2L_SURVEY_QUESTION_ANSWER_OPTIONS;

QUIT;
