ALTER TABLE D2L_ASSIGNMENT_SUMMARY_LOAD
  ADD (
    AIUtilization NUMBER(10) DEFAULT NULL
  )
;
ALTER TABLE D2L_ASSIGNMENT_SUMMARY
  ADD (
    AIUtilization NUMBER(10) DEFAULT NULL
  )
;


ALTER TABLE D2L_ATTENDANCE_REGISTER_LOAD
  ADD (
    DateDeleted TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
    DeletedBy NUMBER(10) DEFAULT NULL
  )
;
ALTER TABLE D2L_ATTENDANCE_REGISTER
  ADD (
    DateDeleted TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
    DeletedBy NUMBER(10) DEFAULT NULL
  )
;


ALTER TABLE D2L_ATTENDANCE_SESSION_LOAD
  ADD (
    DateDeleted TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
    DeletedBy NUMBER(10) DEFAULT NULL
  )
;
ALTER TABLE D2L_ATTENDANCE_SESSION
  ADD (
    DateDeleted TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
    DeletedBy NUMBER(10) DEFAULT NULL
  )
;


ALTER TABLE D2L_ATTENDANCE_USER_SESSION_LOAD
  ADD (
    IsDeleted NUMBER(1) DEFAULT NULL,
    Version NUMBER(20) DEFAULT NULL
  )
;
ALTER TABLE D2L_ATTENDANCE_USER_SESSION
  ADD (
    IsDeleted NUMBER(1) DEFAULT NULL,
    Version NUMBER(20) DEFAULT NULL
  )
;


ALTER TABLE D2L_CONTENT_USER_PROGRESS_LOAD
  ADD (
    Version NUMBER(20) DEFAULT NULL
  )
;
ALTER TABLE D2L_CONTENT_USER_PROGRESS
  ADD (
    Version NUMBER(20) DEFAULT NULL
  )
;


ALTER TABLE D2L_QUESTION_LIBRARY_LOAD
  ADD (
    AIUtilization NUMBER(10) DEFAULT NULL
  )
;
ALTER TABLE D2L_QUESTION_LIBRARY
  ADD (
    AIUtilization NUMBER(10) DEFAULT NULL
  )
;


ALTER TABLE D2L_QUESTION_RELATIONSHIP_LOAD
  MODIFY (
    QuestionVersionId NUMBER(20) NOT NULL
  )
;
ALTER TABLE D2L_QUESTION_RELATIONSHIP
  MODIFY (
    QuestionVersionId NUMBER(20) NOT NULL
  )
;


ALTER TABLE D2L_QUIZ_USER_ANSWER_LOAD
  ADD (
    OutOf DECIMAL(19, 9) DEFAULT NULL,
    TimeStarted TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
    IsBonus NUMBER(1) DEFAULT NULL,
    IsDeleted NUMBER(1) DEFAULT NULL,
    LastModified TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
    LastModifiedBy NUMBER(10) DEFAULT NULL,
    QuizTimeCompleted TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL
  )
;
ALTER TABLE D2L_QUIZ_USER_ANSWER
  ADD (
    OutOf DECIMAL(19, 9) DEFAULT NULL,
    TimeStarted TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
    IsBonus NUMBER(1) DEFAULT NULL,
    IsDeleted NUMBER(1) DEFAULT NULL,
    LastModified TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
    LastModifiedBy NUMBER(10) DEFAULT NULL,
    QuizTimeCompleted TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL
  )
;


ALTER TABLE D2L_QUIZ_USER_ANSWER_RESPONSE_LOAD
  ADD (
    LastModified TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
    IsDeleted NUMBER(1) DEFAULT NULL
  )
;
ALTER TABLE D2L_QUIZ_USER_ANSWER_RESPONSE
  ADD (
    LastModified TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
    IsDeleted NUMBER(1) DEFAULT NULL
  )
;


ALTER TABLE D2L_RELEASE_CONDITION_OBJECT_LOAD
  ADD (
    Guid1 VARCHAR2(36) DEFAULT NULL,
    Guid2 VARCHAR2(36) DEFAULT NULL
  )
;
ALTER TABLE D2L_RELEASE_CONDITION_OBJECT
  ADD (
    Guid1 VARCHAR2(36) DEFAULT NULL,
    Guid2 VARCHAR2(36) DEFAULT NULL
  )
;


ALTER TABLE D2L_SURVEY_USER_ANSWER_LOAD
  ADD (
    IsDeleted NUMBER(1) DEFAULT NULL,
    LastModified TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
    LastModifiedBy NUMBER(10) DEFAULT NULL,
    SurveyTimeCompleted TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL
  )
;
ALTER TABLE D2L_SURVEY_USER_ANSWER
  ADD (
    IsDeleted NUMBER(1) DEFAULT NULL,
    LastModified TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
    LastModifiedBy NUMBER(10) DEFAULT NULL,
    SurveyTimeCompleted TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL
  )
;


ALTER TABLE D2L_SURVEY_USER_ANSWER_RESPONSE_LOAD
  ADD (
    LastModified TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
    IsDeleted NUMBER(1) DEFAULT NULL
  )
;
ALTER TABLE D2L_SURVEY_USER_ANSWER_RESPONSE
  ADD (
    LastModified TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
    IsDeleted NUMBER(1) DEFAULT NULL
  )
;
