ALTER TABLE D2L_AWARD_ISSUED_LOAD DROP (Type, IsRevoked, Credits);
ALTER TABLE D2L_AWARD_ISSUED DROP (Type, IsRevoked, Credits);


ALTER TABLE D2L_CHECKLIST_COMPLETION_LOAD
  ADD (
    IsCompleted NUMBER(1) DEFAULT NULL,
    DateDeleted TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
    DeletedBy NUMBER(10) DEFAULT NULL,
    Version NUMBER(20) DEFAULT NULL
  )
;
ALTER TABLE D2L_CHECKLIST_COMPLETION
  ADD (
    IsCompleted NUMBER(1) DEFAULT NULL,
    DateDeleted TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
    DeletedBy NUMBER(10) DEFAULT NULL,
    Version NUMBER(20) DEFAULT NULL
  )
;


ALTER TABLE D2L_ENROLLMENT_AND_WITHDRAWAL_LOAD DROP (EnrollmentType);
ALTER TABLE D2L_ENROLLMENT_AND_WITHDRAWAL DROP (EnrollmentType);


DROP INDEX D2L_GRADE_SCHEME_LOAD_PK;
ALTER TABLE D2L_GRADE_SCHEME_LOAD DROP (
  GradeSchemeRangeId,
  IsDeleted
);
DELETE FROM
  D2L_GRADE_SCHEME_LOAD
WHERE
  ROWID NOT IN (
    SELECT
      MIN(ROWID)
    FROM
      D2L_GRADE_SCHEME_LOAD
    GROUP BY
      GradeSchemeId
  );
COMMIT;
CREATE UNIQUE INDEX D2L_GRADE_SCHEME_LOAD_PK ON D2L_GRADE_SCHEME_LOAD (GradeSchemeId); 


DROP INDEX D2L_GRADE_SCHEME_PK;
ALTER TABLE D2L_GRADE_SCHEME DROP (
  GradeSchemeRangeId,
  IsDeleted
);
DELETE FROM
  D2L_GRADE_SCHEME
WHERE
  ROWID NOT IN (
    SELECT
      MIN(ROWID)
    FROM
      D2L_GRADE_SCHEME
    GROUP BY
      GradeSchemeId
  );
COMMIT;
CREATE UNIQUE INDEX D2L_GRADE_SCHEME_PK ON D2L_GRADE_SCHEME (GradeSchemeId); 


ALTER TABLE D2L_LTI_LINK_MIGRATION_AUDIT_LOAD
  ADD (
    LegacyURL NVARCHAR2(4000) DEFAULT NULL
  )
;
ALTER TABLE D2L_LTI_LINK_MIGRATION_AUDIT
  ADD (
    LegacyURL NVARCHAR2(4000) DEFAULT NULL
  )
;


ALTER TABLE D2L_QUIZ_ATTEMPT_LOAD DROP (GracePeriod, ExtendedDeadline);
ALTER TABLE D2L_QUIZ_ATTEMPT DROP (GracePeriod, ExtendedDeadline);


ALTER TABLE D2L_QUIZ_OBJECT_LOAD DROP (TimeLimitExceededBehavior, TimeLimitGracePeriod, ShowClock);
ALTER TABLE D2L_QUIZ_OBJECT DROP (TimeLimitExceededBehavior, TimeLimitGracePeriod, ShowClock);


ALTER TABLE D2L_ROLE_DETAIL_LOAD DROP (OrgId, ClassListDisplayRoleCategory, ClassListRoleCategory, ClassListRoleCategoryOrder, Version);
ALTER TABLE D2L_ROLE_DETAIL DROP (OrgId, ClassListDisplayRoleCategory, ClassListRoleCategory, ClassListRoleCategoryOrder, Version);

ALTER TABLE D2L_USER_LOGIN_LOAD DROP (OrgId, TimeOff);
ALTER TABLE D2L_USER_LOGIN DROP (OrgId, TimeOff);

QUIT;
