ALTER TABLE CourseCopyLog_LOAD
  ADD COLUMN `StatusId` INT DEFAULT NULL;

ALTER TABLE CourseCopyLog
  ADD COLUMN `StatusId` INT DEFAULT NULL;

ALTER TABLE LTILink_LOAD
  MODIFY COLUMN `Url` VARCHAR(2000) DEFAULT NULL,
  ADD COLUMN `LastModifiedBy` INT DEFAULT NULL,
  ADD COLUMN `IsDeleted` TINYINT DEFAULT NULL
;

ALTER TABLE LTILink
  MODIFY COLUMN `Url` VARCHAR(2000) DEFAULT NULL,
  ADD COLUMN `LastModifiedBy` INT DEFAULT NULL,
  ADD COLUMN `IsDeleted` TINYINT DEFAULT NULL
;

DROP TABLE LTILinkShared_LOAD;
DROP TABLE LTILinkShared;
DROP TABLE SurveyQuestionAnswerOption_LOAD;
DROP TABLE SurveyQuestionAnswerOption;
