DROP TABLE D2L_COURSE_AWARD;

CREATE TABLE D2L_COURSE_AWARD (
  AssociationId NUMBER(20) NOT NULL,
  AwardId NUMBER(20) DEFAULT NULL,
  OrgUnitId NUMBER(20) DEFAULT NULL,
  DateCreated TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  HiddenAward NUMBER(1) DEFAULT NULL,
  ConditionSetId NUMBER(20) DEFAULT NULL,
  LastModified TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  Credits DECIMAL(9, 2) DEFAULT NULL,
  IsAssociated NUMBER(1) DEFAULT NULL,
  Version NUMBER(20) DEFAULT NULL
);

CREATE UNIQUE INDEX D2L_COURSE_AWARD_PK ON D2L_COURSE_AWARD (
  AssociationId
);

QUIT;
