DROP TABLE D2L_AUDIO_VIDEO_PROCESSED_LOAD;

CREATE TABLE D2L_AUDIO_VIDEO_PROCESSED_LOAD (
  ContentId VARCHAR2(36) NOT NULL,
  RevisionId VARCHAR2(36) NOT NULL,
  RevisionNumber NUMBER(10) DEFAULT NULL,
  Type NVARCHAR2(10) DEFAULT NULL,
  Source NVARCHAR2(64) DEFAULT NULL,
  RevisionSize NUMBER(20) DEFAULT NULL,
  Duration NUMBER(10) DEFAULT NULL,
  RequiredTranscoding NUMBER(1) DEFAULT NULL,
  RequiredTranscribing NUMBER(1) DEFAULT NULL,
  LastModified TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL
);

CREATE UNIQUE INDEX D2L_AUDIO_VIDEO_PROCESSED_LOAD_PK ON D2L_AUDIO_VIDEO_PROCESSED_LOAD (
  ContentId,
  RevisionId
);

QUIT;
